spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        defer-datasource-initialization: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb
    username: root
    password: Jsh8014!
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb